#!/usr/bin/env python3
"""Generate the high-level Java bindings for the openDAQ C API.

Emits, under --output-dir (default src/generated/java):

  com/opendaq/<Class>.java   one wrapper class per openDAQ interface, extending
                             its parent interface's wrapper (root: DaqObject)
  com/opendaq/DaqTypes.java  the Class -> (wrap constructor, interface id)
                             registry behind DaqObject.asType/isA/wrap

Design (mirroring the reference Common Lisp high-level layer, adapted to Java
idiom):

  * methods keep their C stem verbatim (getName/setName/...) as instance
    methods; trailing parameters with C [defaultValue(...)] annotations gain
    trimmed overloads
  * out-parameters become return values; strings, booleans, enums, lists and
    dicts convert to natural Java types (containers per their templateType
    annotations); other interfaces come back wrapped
  * daqBaseObject/boxed-primitive arguments accept plain Java values (boxed
    at the call site), interface arguments take the wrapper class
  * each type's canonical create function becomes a Java constructor, its
    createXxxFromBuilder a constructor overload taking the builder, and every
    other factory a static method keeping its C name
  * classes listed in MANUAL_* tables get hand-written parts injected from
    tools/manual/<Class>.java.inc (readers, packets, callables, ...)

Usage:
    python3 tools/generate_high_level_bindings.py \
        --opendaq-repo tmp/openDAQ --output-dir src/generated/java
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path

from bindings_model import (
    Function,
    JAVA_KEYWORDS,
    Model,
    Param,
    escape_javadoc,
    receiver_class_name,
    strip_daq,
)

HEADER = "// This file is autogenerated by tools/generate_high_level_bindings.py. Do not edit.\n"

MANUAL_DIR = Path(__file__).resolve().parent / "manual"

# --- curation tables --------------------------------------------------------

# Interfaces whose natural Java name collides with java.lang / java.util types
# the generated code itself uses, or with the generated enum names.
CLASS_NAME_OVERRIDES = {
    "daqString": "StringObject",
    "daqInteger": "IntegerObject",
    "daqFloatObject": "FloatObject",
    "daqBoolean": "BooleanObject",
    "daqNumber": "NumberObject",
    "daqList": "ObjectList",
    "daqType": "TypeObject",
    "daqFunction": "FunctionObject",
    # The ICoreType marker interface would collide with the daqCoreType enum.
    "daqCoreType": "CoreTypeObject",
}

# Parents for receivers that have functions but no interface record in the C
# headers (their DECLARE_OPENDAQ_INTERFACE lives in the C++ core headers).
EXTRA_PARENTS = {
    "daqPropertyValueEventArgs": "daqEventArgs",
}

# Functions not surfaced in the high-level layer.
SUPPRESSED_FUNCTIONS = {
    # covered by DaqObject / the runtime
    "daqBaseObject_addRef",
    "daqBaseObject_releaseRef",
    "daqBaseObject_queryInterface",
    "daqBaseObject_borrowInterface",
    # exact duplicates of the canonical constructor
    "daqFloatObject_createFloat",
    "daqBoolean_createBoolean",
    # daqIntfID-typed plumbing with idiomatic equivalents (asType/isA)
    "daqList_createListWithElementType",
    "daqDict_createDictWithExpectedTypes",
    "daqFolderConfig_createFolderWithItemType",
    "daqSearchFilter_createInterfaceIdSearchFilter",
    "daqComponentDeserializeContext_createComponentDeserializeContext",
    # hand-written in tools/manual/ (runtime-typed buffers / callables)
    "daqDataPacket_getData",
    "daqDataPacket_getRawData",
    "daqPropertyObject_getPropertyValue",
    "daqFunction_call",
}

# Classes whose Java constructors are hand-written in tools/manual/ (readers
# built through their builders so skip-events and read types can default).
MANUAL_CONSTRUCTOR_CLASSES = {
    "daqStreamReader",
    "daqTailReader",
    "daqBlockReader",
    "daqMultiReader",
    "daqInstance",  # manual no-arg constructor defaults the module path
}

# openDAQ builds these only through typed factories; the bare class gets no
# constructor (it stays wrappable from a pointer).
NO_DIRECT_CONSTRUCTOR = {
    "daqProperty",
    "daqSearchFilter",
}

# Stems that would collide with (final) java.lang.Object methods.
METHOD_NAME_OVERRIDES = {
    "daqBaseObject_equals": "coreEquals",
    "daqBaseObject_toString": "coreToString",
    "daqAwaitable_wait": "waitCompletion",
}

# Curated defaults for trailing arguments the C headers do not annotate.
OPTIONAL_DEFAULT_OVERRIDES = {
    "daqInstanceBuilder_enableStandardProviders": {"flag": "true"},
}

# The interfaces whose values box/unbox to plain Java scalars.
BOXED_PRIMITIVE_BASES = {
    "daqBaseObject", "daqInteger", "daqFloatObject", "daqBoolean",
    "daqRatio", "daqComplexNumber",
}

# templateType element names with a natural Java form: name -> (java type,
# converter template applied to an owned element pointer).
PRIMITIVE_ELEMENT_TYPES = {
    "String": ("String", "p -> (String) Wrap.unboxOwned(p)"),
    "Int": ("Long", "p -> (Long) Wrap.unboxOwned(p)"),
    "Integer": ("Long", "p -> (Long) Wrap.unboxOwned(p)"),
    "Bool": ("Boolean", "p -> (Boolean) Wrap.unboxOwned(p)"),
    "Boolean": ("Boolean", "p -> (Boolean) Wrap.unboxOwned(p)"),
    "Float": ("Double", "p -> (Double) Wrap.unboxOwned(p)"),
    "Ratio": ("RatioValue", "p -> (RatioValue) Wrap.unboxOwned(p)"),
    "ComplexNumber": ("ComplexValue", "p -> (ComplexValue) Wrap.unboxOwned(p)"),
    "BaseObject": ("Object", "Wrap::unboxOwned"),
    "Number": ("Object", "Wrap::unboxOwned"),
}


def sanitize_method(name: str) -> str:
    return name + "_" if name in JAVA_KEYWORDS else name


@dataclass
class ClassSpec:
    c_name: str
    java: str
    parent_c: str | None            # None only for daqBaseObject
    docstring: str = ""
    functions: list[Function] = field(default_factory=list)
    has_interface_id: bool = False
    primary_ctor: Function | None = None
    builder_ctors: list[Function] = field(default_factory=list)
    static_factories: list[Function] = field(default_factory=list)


class Generator:

    def __init__(self, model: Model):
        self.model = model
        self.classes: dict[str, ClassSpec] = {}          # c name -> spec
        self.enum_javas = {info.java_name for info in model.enums.values()}
        self._build_classes()
        self._assign_functions()
        # (java class, method name, arg type tuple) -> return type, for
        # inherited-signature conflict handling; filled during emission in
        # topological order.
        self.emitted_signatures: dict[str, dict[tuple, str]] = {}

    # -- class table ---------------------------------------------------------

    def java_class(self, c_name: str) -> str:
        if c_name in CLASS_NAME_OVERRIDES:
            return CLASS_NAME_OVERRIDES[c_name]
        return strip_daq(c_name)

    def _build_classes(self) -> None:
        receivers = {f.receiver for f in self.model.functions}
        all_c = set(self.model.interfaces) | (receivers - {"daqBaseObject"})
        all_c.add("daqBaseObject")
        for c_name in sorted(all_c):
            java = self.java_class(c_name)
            if java in self.enum_javas:
                raise ValueError(f"class name {java} collides with an enum; add an override")
            parent = (None if c_name == "daqBaseObject"
                      else self.model.interfaces.get(c_name)
                      or EXTRA_PARENTS.get(c_name, "daqBaseObject"))
            self.classes[c_name] = ClassSpec(
                c_name=c_name, java=java, parent_c=parent,
                docstring=self.model.interface_docs.get(c_name, ""))
        javas = [spec.java for spec in self.classes.values()]
        if len(set(javas)) != len(javas):
            dupes = {j for j in javas if javas.count(j) > 1}
            raise ValueError(f"duplicate Java class names: {dupes}")

    def is_constructor(self, function: Function) -> bool:
        return (function.stem.startswith("create")
                and not function.has_self
                and len(function.outputs) == 1
                and function.outputs[0].c_name == "obj"
                and function.outputs[0].jtype.kind == "pointer"
                and not function.outputs[0].struct_pointee)

    def _assign_functions(self) -> None:
        for function in self.model.functions:
            if function.c_name in SUPPRESSED_FUNCTIONS:
                continue
            if function.stem == "getInterfaceId":
                self.classes[function.receiver].has_interface_id = True
                continue
            if len(function.outputs) > 1 or any(p.struct_pointee for p in function.outputs):
                # Multi-out functions are the raw reader calls (surfaced by the
                # hand-written reader API) and deserialize-context plumbing.
                continue
            spec = self.classes[function.receiver]
            if self.is_constructor(function):
                if function.receiver in NO_DIRECT_CONSTRUCTOR:
                    spec.static_factories.append(function)
                elif function.stem == f"create{strip_daq(function.receiver)}FromBuilder":
                    spec.builder_ctors.append(function)
                else:
                    spec.static_factories.append(function)
            else:
                spec.functions.append(function)
        # Pick each class's primary constructor: create<Receiver> when
        # present, else the first (alphabetical) factory-shaped function whose
        # result type is the receiver itself; everything else stays a factory.
        for spec in self.classes.values():
            if spec.c_name in NO_DIRECT_CONSTRUCTOR or spec.c_name in MANUAL_CONSTRUCTOR_CLASSES:
                continue
            preferred = f"create{strip_daq(spec.c_name)}"
            candidates = [f for f in spec.static_factories
                          if f.outputs[0].base_type == spec.c_name]
            primary = next((f for f in candidates if f.stem == preferred),
                           candidates[0] if candidates else None)
            if primary is not None:
                spec.primary_ctor = primary
                spec.static_factories.remove(primary)

    def topo_order(self) -> list[ClassSpec]:
        ordered: list[ClassSpec] = []
        visited: set[str] = set()

        def visit(c_name: str) -> None:
            if c_name in visited or c_name not in self.classes:
                return
            visited.add(c_name)
            parent = self.classes[c_name].parent_c
            if parent:
                visit(parent)
            ordered.append(self.classes[c_name])

        for c_name in sorted(self.classes):
            visit(c_name)
        return ordered

    # -- parameter/return mapping ---------------------------------------------

    def in_param_java(self, param: Param) -> tuple[str, str]:
        """(java type, boxing kind) for a high-level in-parameter."""
        base = param.base_type
        jt = param.jtype
        if base == "daqString":
            return "String", "daqstring"
        if base == "daqConstCharPtr":
            return "String", "cstring"
        if base in BOXED_PRIMITIVE_BASES and jt.kind == "pointer":
            return "Object", "boxed"
        if base == "daqNumber":
            return "Object", "number"
        if base == "daqList":
            return "java.util.List<?>", "boxlist"
        if base == "daqDict":
            return "java.util.Map<?, ?>", "boxdict"
        if jt.kind in {"bool", "enum", "scalar"}:
            return jt.java, "direct"
        if jt.kind == "pointer":
            if base == "void" or self.model._effective_category(base) == "callback":
                return "MemorySegment", "direct"
            if base in self.classes:
                return self.classes[base].java, "wrapper"
            return "MemorySegment", "direct"
        return "MemorySegment", "direct"

    def element_conversion(self, annotated: str | None) -> tuple[str, str]:
        """(java element type, owned-pointer converter expr) for a container
        templateType name."""
        if annotated is None:
            return "Object", "Wrap::unboxOwned"
        name = annotated.removesuffix("Ptr")
        if name in PRIMITIVE_ELEMENT_TYPES:
            return PRIMITIVE_ELEMENT_TYPES[name]
        c_name = "daq" + name
        if c_name in self.model.enums:
            enum_java = self.model.enums[c_name].java_name
            return enum_java, f"p -> {enum_java}.fromValue(((Long) Wrap.unboxOwned(p)).intValue())"
        if c_name in self.classes:
            java = self.classes[c_name].java
            return java, f"p -> Wrap.castOwned(p, {java}.class)"
        return "Object", "Wrap::unboxOwned"

    def out_java_and_conversion(self, param: Param) -> tuple[str, str]:
        """(java return type, conversion template with {raw} placeholder)."""
        base = param.base_type
        jt = param.jtype
        if base == "daqString":
            return "String", "Ffi.readDaqStringAndRelease({raw})"
        if jt.kind in {"bool", "enum", "scalar"}:
            return jt.java, "{raw}"
        if jt.kind == "pointer":
            if base == "daqList":
                element_java, converter = self.element_conversion(param.value_type)
                return f"java.util.List<{element_java}>", f"Wrap.list({{raw}}, {converter})"
            if base == "daqDict":
                key_java, key_conv = self.element_conversion(param.key_type)
                value_java, value_conv = self.element_conversion(param.value_type)
                return (f"java.util.Map<{key_java}, {value_java}>",
                        f"Wrap.map({{raw}}, {key_conv}, {value_conv})")
            if base in self.classes:
                java = self.classes[base].java
                return java, f"DaqObject.wrap({{raw}}, {java}.class)"
            return "MemorySegment", "{raw}"
        return "MemorySegment", "{raw}"

    # -- defaults ---------------------------------------------------------------

    def java_default(self, literal: str, java_type: str) -> str | None:
        if literal == "nullptr":
            return f"({java_type}) null" if java_type != "MemorySegment" else "MemorySegment.NULL"
        if literal in {"true", "false"}:
            return literal
        try:
            value = int(literal, 0)
        except ValueError:
            return None
        if java_type == "long":
            return f"{value}L"
        return str(value)

    def trailing_defaults(self, function: Function, hl_params: list) -> int:
        """Index of the first defaulted trailing parameter in hl_params (or
        len(hl_params) when none).  hl_params entries are (param, java, kind)."""
        overrides = OPTIONAL_DEFAULT_OVERRIDES.get(function.c_name, {})
        first = len(hl_params)
        for index in range(len(hl_params) - 1, -1, -1):
            param, java, _ = hl_params[index]
            literal = overrides.get(param.c_name, param.default_value)
            if literal is None or self.java_default(literal, java) is None:
                break
            first = index
        return first

    def default_expr(self, function: Function, param: Param, java: str) -> str:
        overrides = OPTIONAL_DEFAULT_OVERRIDES.get(function.c_name, {})
        literal = overrides.get(param.c_name, param.default_value)
        return self.java_default(literal, java)

    # -- emission ---------------------------------------------------------------

    def hl_params(self, function: Function) -> list:
        params = [p for p in function.inputs if p.c_name != "self"]
        return [(p, *self.in_param_java(p)) for p in params]

    def emit_invocation(self, function: Function, spec: ClassSpec,
                        hl_params: list, lines: list[str], indent: str,
                        result_handler) -> None:
        """Emit the boxed low-level invocation.  result_handler(raw_expr,
        indent) appends the lines consuming the call result."""
        needs_arena = any(kind == "cstring" for _, _, kind in hl_params)
        depth = 0
        if needs_arena:
            lines.append(f"{indent}try (Arena arena = Arena.ofConfined()) {{")
            indent += "    "
            depth += 1

        call_args: list[str] = []
        if function.has_self:
            call_args.append("requireLivePointer()")
        for param, java, kind in hl_params:
            name = param.java_name
            if kind == "direct":
                call_args.append(f"Ffi.orNull({name})" if java == "MemorySegment" else name)
            elif kind == "wrapper":
                call_args.append(f"({name} == null ? MemorySegment.NULL : {name}.requireLivePointer())")
            elif kind == "cstring":
                call_args.append(f"({name} == null ? MemorySegment.NULL : arena.allocateFrom({name}))")
            elif kind == "daqstring":
                lines.append(f"{indent}MemorySegment {name}$s = Wrap.daqStringOrNull({name});")
                lines.append(f"{indent}try {{")
                indent += "    "
                depth += 1
                call_args.append(f"{name}$s")
            elif kind == "boxed":
                lines.append(f"{indent}Box.Boxed {name}$b = Box.box({name});")
                lines.append(f"{indent}try {{")
                indent += "    "
                depth += 1
                call_args.append(f"{name}$b.segment()")
            elif kind == "number":
                lines.append(f"{indent}MemorySegment {name}$n = Box.boxNumberOwned({name});")
                lines.append(f"{indent}try {{")
                indent += "    "
                depth += 1
                call_args.append(f"{name}$n")
            elif kind == "boxlist":
                lines.append(f"{indent}MemorySegment {name}$l = ({name} == null ? MemorySegment.NULL : Box.boxListOwned({name}));")
                lines.append(f"{indent}try {{")
                indent += "    "
                depth += 1
                call_args.append(f"{name}$l")
            elif kind == "boxdict":
                lines.append(f"{indent}MemorySegment {name}$d = ({name} == null ? MemorySegment.NULL : Box.boxDictOwned({name}));")
                lines.append(f"{indent}try {{")
                indent += "    "
                depth += 1
                call_args.append(f"{name}$d")
            else:
                raise ValueError(kind)

        low_class = receiver_class_name(function.receiver)
        call = f"{low_class}.{function.stem}({', '.join(call_args)})"
        result_handler(call, indent, lines)

        # Close the nested try blocks with their cleanups, innermost first.
        cleanup_stack = []
        for param, java, kind in hl_params:
            name = param.java_name
            if kind == "daqstring":
                cleanup_stack.append(f"Ffi.releaseRef({name}$s);")
            elif kind == "boxed":
                cleanup_stack.append(f"Box.releaseBoxed({name}$b);")
            elif kind == "number":
                cleanup_stack.append(f"Ffi.releaseRef({name}$n);")
            elif kind in {"boxlist", "boxdict"}:
                suffix = "$l" if kind == "boxlist" else "$d"
                cleanup_stack.append(f"Ffi.releaseRef({name}{suffix});")
        for cleanup in reversed(cleanup_stack):
            indent = indent[:-4]
            lines.append(f"{indent}}} finally {{ {cleanup} }}")
        if needs_arena:
            indent = indent[:-4]
            lines.append(f"{indent}}}")

    def method_doc(self, function: Function, returns_self: bool = False) -> list[str]:
        text = function.docstring.strip()
        if text.startswith("@brief"):
            text = text[len("@brief"):].strip()
        sentence = f"Calls the openDAQ C function {{@code {function.c_name}()}}."
        full = f"{text}\n\n<p>{sentence}" if text else sentence
        out = ["    /**"]
        for line in escape_javadoc(full).split("\n"):
            out.append(("     * " + line).rstrip())
        if returns_self:
            out.append("     * @return this builder, to allow call chaining")
        out.append("     */")
        return out

    def emit_method(self, function: Function, spec: ClassSpec, lines: list[str]) -> None:
        hl_params = self.hl_params(function)
        outs = function.outputs
        if outs:
            ret_java, conversion = self.out_java_and_conversion(outs[0])
        elif not function.is_errcode and function.ret.kind != "void":
            ret_java, conversion = function.ret.java, "{raw}"
        else:
            ret_java, conversion = "void", None

        name = sanitize_method(METHOD_NAME_OVERRIDES.get(function.c_name, function.stem))
        static = not function.has_self
        modifier = "public static" if static else "public"

        # Builder configuration calls (void C setters/adders on a *Builder class)
        # return the builder itself, so they can be chained fluently before the
        # terminal build(): new XBuilder().setA(..).setB(..).build().
        fluent = not static and ret_java == "void" and spec.java.endswith("Builder")
        decl_ret = spec.java if fluent else ret_java

        arg_types = tuple(java for _, java, _ in hl_params)
        signatures = self.emitted_signatures.setdefault(spec.java, {})
        inherited_return = self.inherited_return(spec, name, arg_types)
        if (name, arg_types) in signatures:
            return
        if inherited_return is not None:
            if inherited_return == ret_java or not self.is_subclass_java(ret_java, inherited_return):
                # Same operation declared on an ancestor interface: the C
                # functions hit the same vtable slot, so the inherited method
                # already covers this class.
                return

        first_default = self.trailing_defaults(function, hl_params)

        lines.extend(self.method_doc(function, returns_self=fluent))
        params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in hl_params)
        lines.append(f"    {modifier} {decl_ret} {name}({params_sig}) {{")
        body: list[str] = []

        def handle_result(call: str, indent: str, out: list[str]) -> None:
            if ret_java == "void":
                out.append(f"{indent}{call};")
            else:
                converted = conversion.replace("{raw}", call)
                out.append(f"{indent}return {converted};")

        fence_targets = (["this"] if not static else []) \
            + [p.java_name for p, _, kind in hl_params if kind == "wrapper"]
        indent = "        "
        if fence_targets:
            body.append(f"{indent}try {{")
            self.emit_invocation(function, spec, hl_params, body, indent + "    ", handle_result)
            body.append(f"{indent}}} finally {{")
            for target in fence_targets:
                body.append(f"{indent}    Reference.reachabilityFence({target});")
            body.append(f"{indent}}}")
        else:
            self.emit_invocation(function, spec, hl_params, body, indent, handle_result)
        if fluent:
            body.append(f"{indent}return this;")
        lines.extend(body)
        lines.append("    }")
        lines.append("")
        signatures[(name, arg_types)] = decl_ret

        # Trimmed overloads for trailing defaulted parameters.
        for cut in range(first_default, len(hl_params)):
            head = hl_params[:cut]
            head_types = tuple(java for _, java, _ in head)
            if (name, head_types) in signatures or self.inherited_return(spec, name, head_types) is not None:
                continue
            params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in head)
            call_args = [p.java_name for p, _, _ in head] + [
                self.default_expr(function, p, java) for p, java, _ in hl_params[cut:]]
            lines.append(f"    /** {name} with trailing arguments at their openDAQ defaults. */")
            lines.append(f"    {modifier} {decl_ret} {name}({params_sig}) {{")
            call = f"{name}({', '.join(call_args)})"
            lines.append(f"        {'return ' if decl_ret != 'void' else ''}{call};")
            lines.append("    }")
            lines.append("")
            signatures[(name, head_types)] = decl_ret

    def inherited_return(self, spec: ClassSpec, name: str, arg_types: tuple) -> str | None:
        parent = spec.parent_c
        while parent:
            parent_spec = self.classes.get(parent)
            if parent_spec is None:
                break
            found = self.emitted_signatures.get(parent_spec.java, {}).get((name, arg_types))
            if found is not None:
                return found
            parent = parent_spec.parent_c
        return None

    def is_subclass_java(self, child_java: str, parent_java: str) -> bool:
        child = next((s for s in self.classes.values() if s.java == child_java), None)
        while child is not None:
            if child.java == parent_java:
                return True
            child = self.classes.get(child.parent_c) if child.parent_c else None
        return False

    # -- constructors and factories ----------------------------------------------

    def emit_pointer_helper(self, function: Function, helper: str, lines: list[str]) -> None:
        """private static MemorySegment HELPER(args) performing the boxed
        factory call and returning the raw created pointer."""
        hl_params = self.hl_params(function)
        params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in hl_params)
        lines.append(f"    private static MemorySegment {helper}({params_sig}) {{")
        body: list[str] = []

        def handle_result(call: str, indent: str, out: list[str]) -> None:
            out.append(f"{indent}return {call};")

        fence_targets = [p.java_name for p, _, kind in hl_params if kind == "wrapper"]
        indent = "        "
        if fence_targets:
            body.append(f"{indent}try {{")
            self.emit_invocation(function, None, hl_params, body, indent + "    ", handle_result)
            body.append(f"{indent}}} finally {{")
            for target in fence_targets:
                body.append(f"{indent}    Reference.reachabilityFence({target});")
            body.append(f"{indent}}}")
        else:
            self.emit_invocation(function, None, hl_params, body, indent, handle_result)
        lines.extend(body)
        lines.append("    }")
        lines.append("")

    def emit_constructor(self, function: Function, spec: ClassSpec,
                         ctor_signatures: set, lines: list[str]) -> None:
        hl_params = self.hl_params(function)
        arg_types = tuple(java for _, java, _ in hl_params)
        if arg_types in ctor_signatures or arg_types == ("MemorySegment",):
            # Would collide with the adopting constructor (or another factory):
            # keep it as a static factory instead.
            spec.static_factories.append(function)
            return
        helper = f"create${function.stem}"
        first_default = self.trailing_defaults(function, hl_params)

        lines.extend(self.method_doc(function))
        params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in hl_params)
        lines.append(f"    public {spec.java}({params_sig}) {{")
        lines.append(f"        super({helper}({', '.join(p.java_name for p, _, _ in hl_params)}));")
        lines.append("    }")
        lines.append("")
        ctor_signatures.add(arg_types)
        self.emit_pointer_helper(function, helper, lines)

        for cut in range(first_default, len(hl_params)):
            head = hl_params[:cut]
            head_types = tuple(java for _, java, _ in head)
            if head_types in ctor_signatures or head_types == ("MemorySegment",):
                continue
            params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in head)
            call_args = [p.java_name for p, _, _ in head] + [
                self.default_expr(function, p, java) for p, java, _ in hl_params[cut:]]
            lines.append(f"    /** Constructor with trailing arguments at their openDAQ defaults. */")
            lines.append(f"    public {spec.java}({params_sig}) {{")
            lines.append(f"        this({', '.join(call_args)});")
            lines.append("    }")
            lines.append("")
            ctor_signatures.add(head_types)

    def emit_factory(self, function: Function, spec: ClassSpec, lines: list[str]) -> None:
        result_c = function.outputs[0].base_type
        result_spec = self.classes.get(result_c)
        result_java = result_spec.java if result_spec else "BaseObject"
        hl_params = self.hl_params(function)
        name = sanitize_method(function.stem)
        arg_types = tuple(java for _, java, _ in hl_params)
        signatures = self.emitted_signatures.setdefault(spec.java, {})
        if (name, arg_types) in signatures or self.inherited_return(spec, name, arg_types) is not None:
            return
        helper = f"create${function.stem}"
        first_default = self.trailing_defaults(function, hl_params)

        lines.extend(self.method_doc(function))
        params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in hl_params)
        lines.append(f"    public static {result_java} {name}({params_sig}) {{")
        lines.append(f"        return DaqObject.wrap({helper}({', '.join(p.java_name for p, _, _ in hl_params)}), {result_java}.class);")
        lines.append("    }")
        lines.append("")
        signatures[(name, arg_types)] = result_java
        self.emit_pointer_helper(function, helper, lines)

        for cut in range(first_default, len(hl_params)):
            head = hl_params[:cut]
            head_types = tuple(java for _, java, _ in head)
            if (name, head_types) in signatures or self.inherited_return(spec, name, head_types) is not None:
                continue
            params_sig = ", ".join(f"{java} {p.java_name}" for p, java, _ in head)
            call_args = [p.java_name for p, _, _ in head] + [
                self.default_expr(function, p, java) for p, java, _ in hl_params[cut:]]
            lines.append(f"    /** {name} with trailing arguments at their openDAQ defaults. */")
            lines.append(f"    public static {result_java} {name}({params_sig}) {{")
            lines.append(f"        return {name}({', '.join(call_args)});")
            lines.append("    }")
            lines.append("")
            signatures[(name, head_types)] = result_java

    # -- classes -------------------------------------------------------------------

    def render_class(self, spec: ClassSpec) -> str:
        parent_java = "DaqObject" if spec.parent_c is None else self.classes[spec.parent_c].java
        lines = [HEADER, "package com.opendaq;", ""]
        lines.append("import java.lang.foreign.Arena;")
        lines.append("import java.lang.foreign.MemorySegment;")
        lines.append("import java.lang.foreign.ValueLayout;")
        lines.append("import java.lang.ref.Reference;")
        lines.append("import java.util.List;")
        lines.append("import java.util.Map;")
        lines.append("")
        lines.append("import com.opendaq.lowlevel.*;")
        lines.append("")
        doc = spec.docstring.strip()
        if doc.startswith("@brief"):
            doc = doc[len("@brief"):].strip()
        header_doc = (f"{doc}\n\n<p>" if doc else "") \
            + f"Wraps the openDAQ {{@code {spec.c_name}}} interface."
        lines.append("/**")
        for line in escape_javadoc(header_doc).split("\n"):
            lines.append((" * " + line).rstrip())
        lines.append(" */")
        lines.append(f"public class {spec.java} extends {parent_java} {{")
        lines.append("")
        lines.append("    /** Adopt an owned reference (see {@link DaqObject#DaqObject}). */")
        lines.append(f"    public {spec.java}(MemorySegment pointer) {{")
        lines.append("        super(pointer);")
        lines.append("    }")
        lines.append("")

        ctor_signatures: set = {("MemorySegment",)}
        if spec.primary_ctor is not None:
            self.emit_constructor(spec.primary_ctor, spec, ctor_signatures, lines)
        for builder_ctor in list(spec.builder_ctors):
            self.emit_constructor(builder_ctor, spec, ctor_signatures, lines)

        for factory in sorted(spec.static_factories, key=lambda f: f.stem):
            self.emit_factory(factory, spec, lines)

        for function in sorted(spec.functions, key=lambda f: f.stem):
            self.emit_method(function, spec, lines)

        manual = MANUAL_DIR / f"{spec.java}.java.inc"
        if manual.exists():
            lines.append("    // ------------------------------------------------------------------")
            lines.append(f"    // Hand-written part (tools/manual/{spec.java}.java.inc)")
            lines.append("    // ------------------------------------------------------------------")
            lines.append("")
            lines.append(manual.read_text(encoding="utf-8").rstrip())
            lines.append("")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def render_daq_types(self) -> str:
        lines = [HEADER, "package com.opendaq;", ""]
        lines.append("/** Registers every wrapper class with the runtime type registry. */")
        lines.append("final class DaqTypes {")
        lines.append("")
        lines.append("    private DaqTypes() {}")
        lines.append("")
        lines.append("    static void registerAll() {")
        for spec in sorted(self.classes.values(), key=lambda s: s.java):
            low = receiver_class_name(spec.c_name)
            id_ref = (f"com.opendaq.lowlevel.{low}::getInterfaceId"
                      if spec.has_interface_id else "null")
            lines.append(f"        TypeRegistry.register({spec.java}.class, {spec.java}::new, {id_ref});")
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines) + "\n"


def generate(opendaq_repo: Path, output_dir: Path) -> None:
    model = Model(opendaq_repo)
    generator = Generator(model)
    public_dir = output_dir / "com" / "opendaq"
    public_dir.mkdir(parents=True, exist_ok=True)

    # Clear previously generated high-level classes (identified by the header)
    for existing in public_dir.glob("*.java"):
        if existing.read_text(encoding="utf-8").startswith(HEADER.split("\n")[0]):
            first = existing.read_text(encoding="utf-8").splitlines()[0]
            if "generate_high_level_bindings" in first:
                existing.unlink()

    count = 0
    for spec in generator.topo_order():
        (public_dir / f"{spec.java}.java").write_text(
            generator.render_class(spec), encoding="utf-8")
        count += 1
    (public_dir / "DaqTypes.java").write_text(generator.render_daq_types(), encoding="utf-8")
    print(f"generated {count} high-level classes + DaqTypes registry")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--opendaq-repo", type=Path, required=True,
                        help="Path to the openDAQ repository (containing bindings/c/include/).")
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parents[1] / "src" / "generated" / "java")
    args = parser.parse_args()
    generate(args.opendaq_repo, args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
