#!/usr/bin/env python3
"""Generate the low-level Java FFI bindings for the openDAQ C API.

Emits, under --output-dir (default src/generated/java):

  org/opendaq/lowlevel/Daq<Receiver>.java   one class per C receiver, holding a
                                            checked static wrapper per function
  org/opendaq/lowlevel/ErrorCodes.java      status-code constants and names
  org/opendaq/<EnumName>.java               one Java enum per C enum typedef

Each wrapper method mirrors the reference Common Lisp low-level layer: the
daqErrCode return is checked (throwing org.opendaq.OpenDaqException on
failure), out-parameters become return values (a generated per-function record
when there are several), and in-out parameters appear both as an argument and
in the result.  Functions with a struct out-parameter (the getInterfaceId
family) stay raw: the caller passes the slot.

Usage:
    python3 tools/generate_low_level_bindings.py \
        --opendaq-repo ../cl-opendaq/tmp/openDAQ --output-dir src/generated/java
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from bindings_model import (
    Function,
    Model,
    Param,
    doc_brief,
    escape_javadoc,
    receiver_class_name,
    sanitize_identifier,
)

HEADER = "// This file is autogenerated by tools/generate_low_level_bindings.py. Do not edit.\n"

VALUE_LAYOUTS = {"JAVA_BYTE", "JAVA_SHORT", "JAVA_INT", "JAVA_LONG",
                 "JAVA_FLOAT", "JAVA_DOUBLE", "ADDRESS"}


def layout_expr(layout: str) -> str:
    return layout if layout not in VALUE_LAYOUTS else layout


def descriptor(function: Function) -> str:
    """The FunctionDescriptor expression for FUNCTION's raw C signature."""
    arg_layouts = []
    for param in function.params:
        if param.mode != "in":
            arg_layouts.append("ADDRESS")            # pointer to the out slot
        elif param.jtype.kind == "struct":
            arg_layouts.append("Ffi.INTF_ID")        # by-value daqIntfID
        else:
            arg_layouts.append(param.jtype.layout)
    args = ", ".join(arg_layouts)
    if function.ret.kind == "void":
        return f"FunctionDescriptor.ofVoid({args})" if args else "FunctionDescriptor.ofVoid()"
    ret_layout = "JAVA_INT" if function.is_errcode else function.ret.layout
    return f"FunctionDescriptor.of({ret_layout}{', ' + args if args else ''})"


def handle_field(function: Function) -> str:
    return f'Ffi.require(MH_{function.stem}, "{function.c_name}")'


def java_in_type(param: Param) -> str:
    return param.jtype.java


def slot_layout(param: Param) -> str:
    """Layout of the value stored in an out slot."""
    return param.jtype.layout


def slot_read(param: Param, slot: str) -> str:
    """Expression reading an out slot back as the wrapper's Java value."""
    jt = param.jtype
    if jt.kind == "pointer":
        return f"{slot}.get(ADDRESS, 0)"
    if jt.kind == "bool":
        return f"{slot}.get(JAVA_BYTE, 0) != 0"
    if jt.kind == "enum":
        return f"{jt.java}.fromValue({slot}.get(JAVA_INT, 0))"
    return f"{slot}.get({jt.layout}, 0)"


def slot_write(param: Param, slot: str, value: str) -> str:
    jt = param.jtype
    if jt.kind == "pointer":
        return f"{slot}.set(ADDRESS, 0, Ffi.orNull({value}))"
    if jt.kind == "bool":
        return f"{slot}.set(JAVA_BYTE, 0, (byte) ({value} ? 1 : 0))"
    if jt.kind == "enum":
        return f"{slot}.set(JAVA_INT, 0, {value}.value())"
    return f"{slot}.set({jt.layout}, 0, {value})"


def call_argument(param: Param, slots: dict[str, str]) -> str:
    """The invokeExact argument expression for PARAM."""
    if param.mode != "in":
        return slots[param.c_name]
    jt = param.jtype
    if jt.kind == "pointer" or jt.kind == "struct":
        return f"Ffi.orNull({param.java_name})"
    if jt.kind == "bool":
        return f"(byte) ({param.java_name} ? 1 : 0)"
    if jt.kind == "enum":
        return f"{param.java_name}.value()"
    return param.java_name


def result_record_name(function: Function) -> str:
    return function.stem[0].upper() + function.stem[1:] + "Result"


def wrapper_outputs(function: Function) -> list[Param]:
    outs = list(function.outputs)
    if not function.is_errcode and function.ret.kind != "void":
        return outs
    return outs


def emit_wrapped(function: Function, lines: list[str]) -> None:
    outs = function.outputs
    ins = function.inputs
    record = None
    extra_ret = not function.is_errcode and function.ret.kind != "void"

    # Return type
    ret_values = ([function.ret.java] if extra_ret else []) + [p.jtype.java for p in outs]
    if len(ret_values) == 0:
        ret_java = "void"
    elif len(ret_values) == 1:
        ret_java = ret_values[0]
    else:
        record = result_record_name(function)
        ret_java = record
        components = []
        if extra_ret:
            components.append(f"{function.ret.java} result")
        components.extend(f"{p.jtype.java} {p.java_name}" for p in outs)
        lines.append(f"    /** Result of {{@link #{function.stem}}}. */")
        lines.append(f"    public record {record}({', '.join(components)}) {{}}")
        lines.append("")

    brief = doc_brief(function.docstring)
    doc = (escape_javadoc(brief) + "  " if brief else "")
    lines.append(f"    /** {doc}Calls {{@code {function.c_name}()}}. */")
    params_sig = ", ".join(f"{java_in_type(p)} {p.java_name}" for p in ins)
    lines.append(f"    public static {ret_java} {function.stem}({params_sig}) {{")

    slots = {p.c_name: f"{p.java_name}Slot" for p in outs}
    body_indent = "        "
    if outs:
        lines.append(f"{body_indent}try (Arena arena = Arena.ofConfined()) {{")
        inner = body_indent + "    "
    else:
        lines.append(f"{body_indent}try {{")
        inner = body_indent + "    "

    for p in outs:
        lines.append(f"{inner}MemorySegment {slots[p.c_name]} = arena.allocate({slot_layout(p)});")
        if p.mode == "in-out":
            lines.append(f"{inner}{slot_write(p, slots[p.c_name], p.java_name)};")

    call_args = ", ".join(call_argument(p, slots) for p in function.params)
    if function.ret.kind == "void":
        lines.append(f"{inner}{handle_field(function)}.invokeExact({call_args});")
    elif function.is_errcode:
        lines.append(f"{inner}int err = (int) {handle_field(function)}.invokeExact({call_args});")
        lines.append(f"{inner}Ffi.checkError(err, \"{function.c_name}\");")
    elif function.ret.kind == "bool":
        lines.append(f"{inner}byte rawResult = (byte) {handle_field(function)}.invokeExact({call_args});")
        lines.append(f"{inner}boolean result = rawResult != 0;")
    elif function.ret.kind == "enum":
        lines.append(f"{inner}int rawResult = (int) {handle_field(function)}.invokeExact({call_args});")
        lines.append(f"{inner}{function.ret.java} result = {function.ret.java}.fromValue(rawResult);")
    else:
        lines.append(f"{inner}{function.ret.java} result = ({function.ret.java}) "
                     f"{handle_field(function)}.invokeExact({call_args});")

    reads = ([("result", None)] if extra_ret else []) \
        + [(slot_read(p, slots[p.c_name]), p) for p in outs]
    if record is not None:
        args = ", ".join(expr for expr, _ in reads)
        lines.append(f"{inner}return new {record}({args});")
    elif len(reads) == 1:
        lines.append(f"{inner}return {reads[0][0]};")
    lines.append(f"{body_indent}}} catch (Throwable t) {{ throw Ffi.rethrow(t); }}")
    lines.append("    }")
    lines.append("")


def emit_raw(function: Function, lines: list[str]) -> None:
    """A function with a struct out-slot (getInterfaceId and friends): keep the
    C signature, the caller allocates every out slot."""
    brief = doc_brief(function.docstring)
    doc = (escape_javadoc(brief) + "  " if brief else "")
    lines.append(f"    /** {doc}Calls {{@code {function.c_name}()}} with caller-allocated out slots. */")
    params_sig = []
    for p in function.params:
        if p.mode != "in":
            params_sig.append(f"MemorySegment {p.java_name}")
        else:
            params_sig.append(f"{java_in_type(p)} {p.java_name}")
    ret_java = "void" if (function.is_errcode or function.ret.kind == "void") else function.ret.java
    lines.append(f"    public static {ret_java} {function.stem}({', '.join(params_sig)}) {{")
    call_args = []
    for p in function.params:
        if p.mode != "in":
            call_args.append(f"Ffi.orNull({p.java_name})")
        else:
            call_args.append(call_argument(p, {}))
    call = f"{handle_field(function)}.invokeExact({', '.join(call_args)})"
    lines.append("        try {")
    if function.ret.kind == "void":
        lines.append(f"            {call};")
    elif function.is_errcode:
        lines.append(f"            int err = (int) {call};")
        lines.append(f"            Ffi.checkError(err, \"{function.c_name}\");")
    else:
        lines.append(f"            return ({function.ret.java}) {call};")
    lines.append("        } catch (Throwable t) { throw Ffi.rethrow(t); }")
    lines.append("    }")
    lines.append("")


def render_receiver_class(receiver: str, functions: list[Function]) -> str:
    class_name = receiver_class_name(receiver)
    lines = [HEADER, "package org.opendaq.lowlevel;", ""]
    lines.append("import java.lang.foreign.Arena;")
    lines.append("import java.lang.foreign.FunctionDescriptor;")
    lines.append("import java.lang.foreign.MemorySegment;")
    lines.append("import java.lang.invoke.MethodHandle;")
    lines.append("")
    lines.append("import static java.lang.foreign.ValueLayout.*;")
    enum_imports = sorted({p.jtype.java for f in functions for p in f.params
                           if p.jtype.kind == "enum"}
                          | ({f.ret.java for f in functions if f.ret.kind == "enum"}))
    for enum_name in enum_imports:
        lines.append(f"import org.opendaq.{enum_name};")
    lines.append("")
    lines.append(f"/** Raw FFI bindings for the {receiver}_* functions of the openDAQ C API. */")
    lines.append(f"public final class {class_name} {{")
    lines.append("")
    lines.append(f"    private {class_name}() {{}}")
    lines.append("")
    for function in functions:
        lines.append(f"    private static final MethodHandle MH_{function.stem} =")
        lines.append(f"        Ffi.downcallOrNull(\"{function.c_name}\", {descriptor(function)});")
    lines.append("")
    for function in functions:
        if function.auto_wrap:
            emit_wrapped(function, lines)
        else:
            emit_raw(function, lines)
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_enum(info) -> str:
    lines = [HEADER, "package org.opendaq;", ""]
    lines.append(f"/** The openDAQ {{@code {info.c_name}}} enumeration. */")
    lines.append(f"public enum {info.java_name} {{")
    for index, (name, value) in enumerate(info.entries):
        suffix = "," if index < len(info.entries) - 1 else ";"
        lines.append(f"    {name}({value}){suffix}")
    lines.append("")
    lines.append("    private final int value;")
    lines.append("")
    lines.append(f"    {info.java_name}(int value) {{")
    lines.append("        this.value = value;")
    lines.append("    }")
    lines.append("")
    lines.append("    /** The raw C enum value. */")
    lines.append("    public int value() {")
    lines.append("        return value;")
    lines.append("    }")
    lines.append("")
    lines.append("    /** The constant for a raw C enum value (first match on duplicates). */")
    lines.append(f"    public static {info.java_name} fromValue(int value) {{")
    lines.append(f"        for ({info.java_name} entry : values()) {{")
    lines.append("            if (entry.value == value) return entry;")
    lines.append("        }")
    lines.append(f"        throw new IllegalArgumentException(\"Unknown {info.java_name} value: \" + value);")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_error_codes(error_codes: list[tuple[int, str]]) -> str:
    lines = [HEADER, "package org.opendaq.lowlevel;", ""]
    lines.append("import java.util.Map;")
    lines.append("import java.util.HashMap;")
    lines.append("")
    lines.append("/**")
    lines.append(" * openDAQ status codes and their upstream symbolic names, gathered from the")
    lines.append(" * errors.h headers of the C bindings.  Only used to label codes in error")
    lines.append(" * reports; control flow keys off the high bit alone (Ffi.isFailure), and the")
    lines.append(" * descriptive message comes from the error-info API.")
    lines.append(" */")
    lines.append("public final class ErrorCodes {")
    lines.append("")
    lines.append("    private ErrorCodes() {}")
    lines.append("")
    for code, name in error_codes:
        literal = f"0x{code:08X}"
        lines.append(f"    public static final int {name} = {literal};")
    lines.append("")
    lines.append("    private static final Map<Integer, String> NAMES = new HashMap<>();")
    lines.append("")
    lines.append("    static {")
    for code, name in error_codes:
        lines.append(f"        NAMES.put(0x{code:08X}, \"{name}\");")
    lines.append("    }")
    lines.append("")
    lines.append("    /** The symbolic name of a status code, or null when unknown. */")
    lines.append("    public static String name(int code) {")
    lines.append("        return NAMES.get(code);")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def generate(opendaq_repo: Path, output_dir: Path) -> None:
    model = Model(opendaq_repo)

    lowlevel_dir = output_dir / "org" / "opendaq" / "lowlevel"
    public_dir = output_dir / "org" / "opendaq"
    if lowlevel_dir.exists():
        shutil.rmtree(lowlevel_dir)
    lowlevel_dir.mkdir(parents=True, exist_ok=True)
    public_dir.mkdir(parents=True, exist_ok=True)

    for receiver, functions in sorted(model.functions_by_receiver().items()):
        class_name = receiver_class_name(receiver)
        path = lowlevel_dir / f"{class_name}.java"
        path.write_text(render_receiver_class(receiver, functions), encoding="utf-8")

    for info in sorted(model.enums.values(), key=lambda e: e.java_name):
        path = public_dir / f"{info.java_name}.java"
        path.write_text(render_enum(info), encoding="utf-8")

    (lowlevel_dir / "ErrorCodes.java").write_text(
        render_error_codes(model.error_codes), encoding="utf-8")

    print(f"generated {len(model.functions_by_receiver())} low-level classes, "
          f"{len(model.enums)} enums, {len(model.error_codes)} error codes")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--opendaq-repo", type=Path, required=True,
                        help="Path to the openDAQ repository (containing bindings/c/include/).")
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parents[1] / "src" / "generated" / "java")
    args = parser.parse_args()
    generate(args.opendaq_repo, args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
